### ISSUE TITLE
Test the contract

### ISSUE THREAD

**Issue by socr102** [paramsNFT/nft_staking#1]
I am trying to test the contract on localhost and devent
In the main.ts, I found these
How to fill these keys?
Where can I find these values?
export const POOL_AUTHORITY = new anchor.web3.PublicKey(
    ""
)

export const POOL_ID = new anchor.web3.PublicKey(
    ""
)

export const CONFIG_ID = new anchor.web3.PublicKey(
    ""
)

**Comment by Sigismund-Params** [comment]
Hi Socr102

If you want to have your own pool, you will have your wallet key (a test one) ready on localhost or devnet, then run the pool.ts under client to initialize your own pool. You will also have your own key for the reward token and the key for the vault where has the reward token ready. You will also need to define the total stakable nft count when you initialize the pool. You can find all the required settings in func initializePool .

A production project using this repo can be found here: https://params.art/stake

**Comment by ljx0520** [comment]
Close this as this has been resolved
